import = [
   "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Block"


[font]
size = 11

# "MesloLGS Nerd Font"
# "JetBrainsMono Nerd Font"
[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[window]
blur = true
opacity = 0.95

[selection]
save_to_clipboard= true
